### upload single file
POST {{baseUrl}}/file?filename=test.gpx
Accept: application/json
Content-Type: text/plain

< data/test.gpx

> {% client.global.set("fileId", response.body.id) %}

### upload multipart
POST {{baseUrl}}/files
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file.txt"

< data/test.txt
--WebAppBoundary--


### get file
GET {{baseUrl}}/files/{{fileId}}
Accept: */*

### download file
GET {{baseUrl}}/files/{{fileId}}?m=dl
Accept: */*

### delete file
DELETE {{baseUrl}}/files/{{fileId}}
Accept: */*

### merge files
POST {{baseUrl}}/merge?fileId={{fileId}}

> {% client.global.set("fileId", response.body.id) %}
